const classesKeyedJSON = {
    "Fighter": {
       "Certification": "Axe D, Bow D, or Brawl D",
       "Level Seal": "Beginner",
       "Proficiency": "Axe +1, Bow +1, Brawl +1",
       "Abilities": "",
       "Mastery Abilities": "Shove, Strength + 2",
       "Specific": "",
    },
    "Monk": {
       "Certification": "Reason D, or Faith D. Can use magic.",
       "Level Seal": "Beginner",
       "Proficiency": "Faith +1, Reason +1",
       "Abilities": "",
       "Mastery Abilities": "Draw Back, Magic +2",
       "Specific": "",
    },
    "Myrmidon": {
       "Certification": "Sword D",
       "Level Seal": "Beginner",
       "Proficiency": "Sword +1",
       "Abilities": "",
       "Mastery Abilities": "Speed +2, Swap",
       "Specific": "",
    },
    "Soldier": {
       "Certification": "Lance D",
       "Level Seal": "Beginner",
       "Proficiency": "Lance +1",
       "Abilities": "",
       "Mastery Abilities": "Defense +2, Reposition",
       "Specific": "",
    },
    "Archer": {
       "Certification": "Bow C",
       "Level Seal": "Intermediate",
       "Proficiency": "Bow +2, Sword +1",
       "Abilities": "Bowrange +1",
       "Mastery Abilities": "Hit +20",
       "Specific": "",
    },
    "Armored Knight": {
       "Certification": "Axe C, Heavy Armor D",
       "Level Seal": "Intermediate",
       "Proficiency": "Axe +2, Hvy Armor +2, Lance +1",
       "Abilities": "",
       "Mastery Abilities": "Armored Blow",
       "Specific": "",
    },
    "Brawler": {
       "Certification": "Brawl C",
       "Level Seal": "Intermediate",
       "Proficiency": "Axe +1, Brawl +2",
       "Abilities": "Unarmed Combat",
       "Mastery Abilities": "Unarmed Combat",
       "Specific": "Male only",
    },
    "Brigand": {
       "Certification": "Axe C",
       "Level Seal": "Intermediate",
       "Proficiency": "Axe +2, Brawl +1",
       "Abilities": "",
       "Mastery Abilities": "Death Blow",
       "Specific": "",
    },
    "Cavalier": {
       "Certification": "Lance C, Riding D",
       "Level Seal": "Intermediate",
       "Proficiency": "Lance +2, Riding +2, Sword +1",
       "Abilities": "Canto",
       "Mastery Abilities": "Desperation",
       "Specific": "",
    },
    "Dark Mage": {
       "Certification": "Reason C, Dark Seal. Can use magic.",
       "Level Seal": "Intermediate",
       "Proficiency": "Faith +1, Reason +2",
       "Abilities": "Heartseeker, Miasma",
       "Mastery Abilities": "Poison Strike",
       "Specific": "Male only",
    },
    "Mage": {
       "Certification": "Reason C. Can use magic.",
       "Level Seal": "Intermediate",
       "Proficiency": "Faith +1, Reason +2",
       "Abilities": "Fire",
       "Mastery Abilities": "Fiendish Blow",
       "Specific": "",
    },
    "Mercenary": {
       "Certification": "Sword C",
       "Level Seal": "Intermediate",
       "Proficiency": "Axe +1, Sword +2",
       "Abilities": "",
       "Mastery Abilities": "Vantage",
       "Specific": "",
    },
    "Pegasus Knight": {
       "Certification": "Lance C, Flying D",
       "Level Seal": "Intermediate",
       "Proficiency": "Flying +2, Lance +2, Sword +1",
       "Abilities": "Avo +10, Canto",
       "Mastery Abilities": "Darting Blow, Triangle Attack",
       "Specific": "Female only",
    },
    "Priest": {
       "Certification": "Faith C. Can use magic.",
       "Level Seal": "Intermediate",
       "Proficiency": "Faith +2, Reason +1",
       "Abilities": "Heal, White Magic Heal +5",
       "Mastery Abilities": "Miracle",
       "Specific": "",
    },
    "Thief": {
       "Certification": "Sword C",
       "Level Seal": "Intermediate",
       "Proficiency": "Bow +1, Sword +2",
       "Abilities": "Locktouch, Steal",
       "Mastery Abilities": "Steal",
       "Specific": "",
    },
    "Bow Knight": {
       "Certification": "Lance C, Bow A, Riding A",
       "Level Seal": "Master",
       "Proficiency": "Bow +3, Lance +3, Riding +3",
       "Abilities": "Bowfaire, Bowrange +2, Canto",
       "Mastery Abilities": "Defiant Spd",
       "Specific": "",
    },
    "Dark Knight": {
       "Certification": "Lance C, Reason B+, Riding A. Can use magic",
       "Level Seal": "Master",
       "Proficiency": "Lance +3, Reason +3, Riding +3",
       "Abilities": "Black Tomefaire, Canto, Dark Tomefaire",
       "Mastery Abilities": "Seal Resistance",
       "Specific": "",
    },
    "Falcon Knight": {
       "Certification": "Sword C, Lance A, Flying B+",
       "Level Seal": "Master",
       "Proficiency": "Flying +3, Lance +3, Sword +3",
       "Abilities": "Avo +10, Canto, Lancefaire",
       "Mastery Abilities": "Defiant Avo",
       "Specific": "Female only",
    },
    "Great Knight": {
       "Certification": "Axe B+, Heavy Armor A, Riding B+",
       "Level Seal": "Master",
       "Proficiency": "Axe +3, Hvy Armor +3, Lance +3",
       "Abilities": "Axefaire, Canto, Lancefaire",
       "Mastery Abilities": "Defiant Def",
       "Specific": "",
    },
    "Gremory": {
       "Certification": "Reason A, Faith A. Can use magic",
       "Level Seal": "Master",
       "Proficiency": "Faith +3, Reason +3",
       "Abilities": "Black Magic Uses x2, Dark Magic Uses x2, White Magic Uses x2",
       "Mastery Abilities": "Defiant Mag",
       "Specific": "Female only",
    },
    "Holy Knight": {
       "Certification": "Lance C, Faith B+, Riding A. Can use magic",
       "Level Seal": "Master",
       "Proficiency": "Faith +3, Lance +3, Riding +3",
       "Abilities": "Canto, Terrain Resistance, White Tomefaire",
       "Mastery Abilities": "Defiant Res",
       "Specific": "",
    },
    "Mortal Savant": {
       "Certification": "Sword A, Reason B+. Can use magic",
       "Level Seal": "Master",
       "Proficiency": "Reason +3, Sword +3",
       "Abilities": "Black Tomefaire, Swordfaire",
       "Mastery Abilities": "Warding Blow",
       "Specific": "",
    },
    "War Master": {
       "Certification": "Axe A, Brawl A",
       "Level Seal": "Master",
       "Proficiency": "Axe +3, Brawl +3",
       "Abilities": "Axefaire, Crit +20, Fistfaire",
       "Mastery Abilities": "Quick Riposte, War Master's Strike",
       "Specific": "Male only",
    },
    "Wyvern Lord": {
       "Certification": "Lance C, Axe A, Flying A",
       "Level Seal": "Master",
       "Proficiency": "Axe +3, Flying +3, Lance +3",
       "Abilities": "Avo +10, Axefaire, Canto",
       "Mastery Abilities": "Defiant Crit",
       "Specific": "",
    },
    "Armored Lord": {
       "Certification": "Start of Chapter 13",
       "Level Seal": "Lord",
       "Proficiency": "Authority +3, Axe +3, Hvy Armor +3",
       "Abilities": "Axefaire, Charm",
       "Mastery Abilities": "Pomp & Circumstance",
       "Specific": "Edelgard only",
    },
    "Barbarossa": {
       "Certification": "Start of Chapter 17",
       "Level Seal": "Lord",
       "Proficiency": "Authority +3, Bow +3, Flying +3",
       "Abilities": "Bowfaire, Canto, Charm",
       "Mastery Abilities": "Wind God",
       "Specific": "Claude only",
    },
    "Emperor": {
       "Certification": "Start of Chapter 16",
       "Level Seal": "Lord",
       "Proficiency": "Authority +3, Axe +3, Hvy Armor +3",
       "Abilities": "Axefaire, Charm",
       "Mastery Abilities": "Flickering Flower",
       "Specific": "Edelgard only",
    },
    "Great Lord": {
       "Certification": "Start of Chapter 16",
       "Level Seal": "Lord",
       "Proficiency": "Authority +3, Lance +3, Sword +3",
       "Abilities": "Charm, Lancefaire",
       "Mastery Abilities": "Paraselene",
       "Specific": "Dimitri only",
    },
    "High Lord": {
       "Certification": "Start of Chapter 13",
       "Level Seal": "Lord",
       "Proficiency": "Authority +3, Lance +3, Sword +3",
       "Abilities": "Charm, Lancefaire",
       "Mastery Abilities": "Pomp & Circumstance",
       "Specific": "Dimitri only",
    },
    "Lord": {
       "Certification": "Sword D+, Authority C",
       "Level Seal": "Lord",
       "Proficiency": "Authority +2, Lance +1, Sword +2",
       "Abilities": "Charm",
       "Mastery Abilities": "Resistance +2, Subdue",
       "Specific": "House Leaders only",
    },
    "Wyvern Master": {
       "Certification": "Start of Chapter 13",
       "Level Seal": "Lord",
       "Proficiency": "Authority +3, Bow +3, Flying +3",
       "Abilities": "Bowfaire, Canto, Charm",
       "Mastery Abilities": "Pomp & Circumstance",
       "Specific": "Claude only",
    },
    "Commoner": {
       "Certification": "Can use magic at half uses",
       "Level Seal": "Unique",
       "Proficiency": "",
       "Abilities": "",
       "Mastery Abilities": "HP +5",
       "Specific": "",
    },
    "Noble": {
       "Certification": "Can use magic at half uses",
       "Level Seal": "Unique",
       "Proficiency": "",
       "Abilities": "",
       "Mastery Abilities": "HP +5",
       "Specific": "",
    },
    "Dancer": {
       "Certification": "Win the White Heron Cup. Can use magic",
       "Level Seal": "Unique",
       "Proficiency": "Authority +2, Sword +2",
       "Abilities": "Dance",
       "Mastery Abilities": "Special Dance",
       "Specific": "",
    },
    "Enlightened One": {
       "Certification": "Start of Chapter 11. Can use magic",
       "Level Seal": "Unique",
       "Proficiency": "Authority +3, Brawl +2, Faith +3, Sword +3",
       "Abilities": "Swordfaire, Terrain Resistance",
       "Mastery Abilities": "Sacred Power",
       "Specific": "Byleth only",
    },
    "Archbishop": {
       "Certification": "Can use magic",
       "Level Seal": "Unique",
       "Proficiency": "Authority +3, Faith +3, Sword +3",
       "Abilities": "Charm, Commander, Terrain Resistance",
       "Mastery Abilities": "Sacred Power",
       "Specific": "Rhea only",
    },
    "Death Knight": {
       "Certification": "Can use magic",
       "Level Seal": "",
       "Proficiency": "Lance +3, Reason +3, Riding +3",
       "Abilities": "Canto, Lancefaire",
       "Mastery Abilities": "Counterattack",
       "Specific": "Death Knight only",
    },
    "Swordmaster": {
       "Certification": "Sword A",
       "Level Seal": "Advanced",
       "Proficiency": "Sword +3",
       "Abilities": "Sword Critical +10, Swordfaire",
       "Mastery Abilities": "Astra",
       "Specific": "",
    },
    "Hero": {
       "Certification": "Sword B, Axe C",
       "Level Seal": "Advanced",
       "Proficiency": "Axe +2, Sword +3",
       "Abilities": "Swordfaire, Vantage",
       "Mastery Abilities": "Defiant Str",
       "Specific": "Male only",
       "Charactes": ""
    },
    "Assassin": {
       "Certification": "Sword B, Bow C",
       "Level Seal": "Advanced",
       "Proficiency": "Bow +2, Sword +3",
       "Abilities": "Locktouch, Stealth, Swordfaire",
       "Mastery Abilities": "Assassinate, Lethality",
       "Specific": "",
    },
    "Paladin": {
       "Certification": "Lance B, Riding B",
       "Level Seal": "Advanced",
       "Proficiency": "Lance +3, Riding +3, Sword +2",
       "Abilities": "Canto, Lancefaire, Terrain Resistance",
       "Mastery Abilities": "Aegis",
       "Specific": "",
    },
    "Warrior": {
       "Certification": "Axe A",
       "Level Seal": "Advanced",
       "Proficiency": "Axe +3",
       "Abilities": "Axe Critical +10, Axefaire",
       "Mastery Abilities": "Wrath",
       "Specific": "",
    },
    "Fortress Knight": {
       "Certification": "Axe B, Heavy Armor B",
       "Level Seal": "Advanced",
       "Proficiency": "Axe +3, Hvy Armor +3, Lance +2",
       "Abilities": "Axefaire, Weight -5",
       "Mastery Abilities": "Pavise",
       "Specific": "",
    },
    "Wyvern Rider": {
       "Certification": "Axe B, Flying C",
       "Level Seal": "Advanced",
       "Proficiency": "Axe +3, Flying +3, Lance +2",
       "Abilities": "Axefaire, Canto",
       "Mastery Abilities": "Seal Defense",
       "Specific": "",
    },
    "Sniper": {
       "Certification": "Bow A",
       "Level Seal": "Advanced",
       "Proficiency": "Bow +3",
       "Abilities": "Bowfaire, Bowrange +1",
       "Mastery Abilities": "Hunter's Volley",
       "Specific": "",
    },
    "Grappler": {
       "Certification": "Brawl A",
       "Level Seal": "Advanced",
       "Proficiency": "Brawl +3",
       "Abilities": "Fistfaire, Unarmed Combat",
       "Mastery Abilities": "Fierce Iron Fist, Tomebreaker",
       "Specific": "Male only",
    },
    "Warlock": {
       "Certification": "Reason A. Can use magic",
       "Level Seal": "Advanced",
       "Proficiency": "Faith +2, Reason +3",
       "Abilities": "Black Magic Uses x2, Black Tomefaire",
       "Mastery Abilities": "Bowbreaker",
       "Specific": "",
    },
    "Dark Bishop": {
       "Certification": "Reason A (Dark Mage qualification Dark Seal)",
       "Level Seal": "Advanced",
       "Proficiency": "Faith +2, Reason +3",
       "Abilities": "Fiendish Blow, Heartseeker, Miasma",
       "Mastery Abilities": "Lifetaker",
       "Specific": "Male only",
    },
    "Bishop": {
       "Certification": "Faith A. Can use magic",
       "Level Seal": "Advanced",
       "Proficiency": "Faith +3, Reason +2",
       "Abilities": "Terrain Resistance, White Magic Heal +10, White Magic Uses x2",
       "Mastery Abilities": "Renewal",
       "Specific": "",
    }
 }

//  module.exports = classesKeyedJSON
export { classesKeyedJSON }